package autoreply

import "testing"

// TestIsAutoGeneratedBareLF proves the #22-5 fix at this site: RFC 3834 loop-
// protection header detection works on bare-LF messages, not only CRLF ones.
// Before normalization a bare-LF message collapsed to one line and its
// Auto-Submitted/Precedence/List-* markers were never seen → auto-reply loops.
func TestIsAutoGeneratedBareLF(t *testing.T) {
	cases := []struct {
		name string
		raw  string
		want bool
	}{
		{"crlf auto-submitted", "From: a@x\r\nAuto-Submitted: auto-replied\r\n\r\nbody", true},
		{"bare-lf auto-submitted", "From: a@x\nAuto-Submitted: auto-replied\n\nbody", true},
		{"bare-lf precedence bulk", "From: a@x\nPrecedence: bulk\n\nbody", true},
		{"bare-lf list-id", "From: a@x\nList-Id: <l.x>\n\nbody", true},
		{"crlf normal", "From: a@x\r\nSubject: hi\r\n\r\nbody", false},
		{"bare-lf normal", "From: a@x\nSubject: hi\n\nbody", false},
		{"bare-lf auto-submitted no", "From: a@x\nAuto-Submitted: no\n\nbody", false},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := isAutoGenerated([]byte(c.raw)); got != c.want {
				t.Fatalf("isAutoGenerated = %v, want %v", got, c.want)
			}
		})
	}
}

// TestNormalizeEOL covers the line-ending canonicalization.
func TestNormalizeEOL(t *testing.T) {
	cases := []struct{ in, out string }{
		{"a\nb", "a\r\nb"},
		{"a\r\nb", "a\r\nb"},
		{"a\rb", "a\r\nb"},
		{"a\r\n\r\nb", "a\r\n\r\nb"},
		{"a\n\nb", "a\r\n\r\nb"},
		{"plain", "plain"},
		{"", ""},
	}
	for _, c := range cases {
		if got := normalizeEOL(c.in); got != c.out {
			t.Fatalf("normalizeEOL(%q) = %q, want %q", c.in, got, c.out)
		}
	}
}
