// Package autoreply implements the JMAP vacation-response auto-reply: when a
// message is delivered to an account with an enabled VacationResponse, and this
// sender has not been auto-replied to within the dedup window, it composes and
// enqueues a reply through the shared outbound queue.
package autoreply

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/Mininglamp-OSS/octo-mail/core/store"
)

// Submitter enqueues the reply (satisfied by *submit.Submitter).
type Submitter interface {
	Submit(ctx context.Context, tenantID, accountID int64, mailFrom string, rcptTo []string, raw []byte) ([]int64, error)
}

// AccountLookup resolves an account id to a store.Account and its tenant id.
type AccountLookup func(ctx context.Context, accountID int64) (store.Account, int64, string, error)

// Responder holds the wiring for vacation auto-replies.
type Responder struct {
	Lookup    AccountLookup
	Submitter Submitter
	// Now is injectable for tests; defaults to time.Now.
	Now func() time.Time
}

// Respond checks the recipient account's vacation config and, if enabled and not
// already replied to this sender within the window, enqueues an auto-reply from
// recipient to sender. Best-effort: errors are returned for logging, not fatal.
func (r *Responder) Respond(ctx context.Context, accountID int64, sender, recipient string, raw []byte) error {
	// RFC 3834 loop protection: never auto-reply to bulk/list/auto-generated mail
	// or to another auto-responder, or we ping-pong. Check the message headers
	// (Auto-Submitted, Precedence, List-*) before anything else.
	if isAutoGenerated(raw) {
		return nil
	}
	acc, tenantID, _, err := r.Lookup(ctx, accountID)
	if err != nil {
		return err
	}
	v, ok, err := acc.VacationGet(ctx)
	if err != nil || !ok || !v.Enabled {
		return err
	}
	// Honor optional active window.
	now := time.Now
	if r.Now != nil {
		now = r.Now
	}
	t := now()
	if !v.FromDate.IsZero() && t.Before(v.FromDate) {
		return nil
	}
	if !v.ToDate.IsZero() && t.After(v.ToDate) {
		return nil
	}
	// Don't auto-reply to automated senders (basic loop protection).
	if isAutomated(sender) {
		return nil
	}
	// Dedup: at most one reply per sender per window.
	should, err := acc.VacationShouldReply(ctx, sender)
	if err != nil || !should {
		return err
	}

	subject := v.Subject
	if subject == "" {
		subject = "Auto-reply"
	}
	msg := buildReply(recipient, sender, subject, v.TextBody)
	_, err = r.Submitter.Submit(ctx, tenantID, accountID, recipient, []string{sender}, msg)
	return err
}

// isAutomated returns true for senders we must never auto-reply to (empty
// return-path, mailer-daemon, no-reply, list traffic) to avoid mail loops.
func isAutomated(sender string) bool {
	if sender == "" {
		return true
	}
	l := strings.ToLower(sender)
	local := l
	if i := strings.IndexByte(l, '@'); i >= 0 {
		local = l[:i]
	}
	for _, bad := range []string{"mailer-daemon", "postmaster", "no-reply", "noreply", "bounce", "bounces"} {
		if strings.Contains(local, bad) {
			return true
		}
	}
	return false
}

// buildReply composes a minimal RFC822 auto-reply with the Auto-Submitted header
// (RFC 3834) so downstream servers recognize it and don't loop.
func buildReply(from, to, subject, text string) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "From: %s\r\n", from)
	fmt.Fprintf(&b, "To: %s\r\n", to)
	fmt.Fprintf(&b, "Subject: %s\r\n", subject)
	b.WriteString("Auto-Submitted: auto-replied\r\n")
	b.WriteString("MIME-Version: 1.0\r\n")
	b.WriteString("Content-Type: text/plain; charset=utf-8\r\n")
	b.WriteString("\r\n")
	b.WriteString(text)
	if !strings.HasSuffix(text, "\n") {
		b.WriteString("\r\n")
	}
	return []byte(b.String())
}

// isAutoGenerated reports whether the inbound message is bulk/list/auto-generated
// mail that RFC 3834 forbids auto-replying to. Checks the header block only:
// Auto-Submitted (anything other than "no"), Precedence: bulk/list/junk, and any
// List-Id / List-Unsubscribe (mailing-list markers).
func isAutoGenerated(raw []byte) bool {
	s := string(raw)
	if i := strings.Index(s, "\r\n\r\n"); i >= 0 {
		s = s[:i]
	}
	// Unfold, then scan header lines.
	s = strings.ReplaceAll(s, "\r\n\t", "\t")
	s = strings.ReplaceAll(s, "\r\n ", " ")
	for _, line := range strings.Split(s, "\r\n") {
		i := strings.IndexByte(line, ':')
		if i < 0 {
			continue
		}
		name := strings.ToLower(strings.TrimSpace(line[:i]))
		val := strings.ToLower(strings.TrimSpace(line[i+1:]))
		switch name {
		case "auto-submitted":
			// RFC 3834: reply only when the value is exactly "no".
			if val != "no" {
				return true
			}
		case "precedence":
			if strings.Contains(val, "bulk") || strings.Contains(val, "list") || strings.Contains(val, "junk") {
				return true
			}
		case "list-id", "list-unsubscribe", "list-post":
			return true
		}
	}
	return false
}
